DROP TABLE RESERVE;
DROP TABLE BOAT;
DROP TABLE SAILOR;

CREATE TABLE SAILOR(
SID VARCHAR(5) NOT NULL PRIMARY KEY,
SNAME CHAR(10) NOT NULL,
RATING INT,
AGE INT
);

INSERT INTO SAILOR(SID,SNAME,RATING,AGE)VALUES('121','A',3,22);
INSERT INTO SAILOR(SID,SNAME,RATING,AGE)VALUES('122','B',4,23);
INSERT INTO SAILOR(SID,SNAME,RATING,AGE)VALUES('123','C',4,24);
INSERT INTO SAILOR(SID,SNAME,RATING,AGE)VALUES('124','D',5,25);
INSERT INTO SAILOR(SID,SNAME,RATING,AGE)VALUES('125','E',3,26);

SELECT *FROM SAILOR;

CREATE TABLE BOAT(
BID VARCHAR(5) NOT NULL PRIMARY KEY,
BNAME CHAR(10) NOT NULL,
COLOR CHAR(10) NOT NULL
);

INSERT INTO BOAT(BID,BNAME,COLOR)VALUES('101','F','RED');
INSERT INTO BOAT(BID,BNAME,COLOR)VALUES('102','G','GREEN');
INSERT INTO BOAT(BID,BNAME,COLOR)VALUES('103','H','BLACK');
INSERT INTO BOAT(BID,BNAME,COLOR)VALUES('104','I','BLUE');
SELECT *FROM BOAT;

 
CREATE TABLE RESERVE(
SID VARCHAR(5) NOT NULL REFERENCES SAILOR(SID),
BID VARCHAR(5) NOT NULL REFERENCES BOAT(BID),
DAY DATE
); 

INSERT INTO RESERVE(SID,BID,DAY)VALUES('121','101','10-JAN-2016');
INSERT INTO RESERVE(SID,BID,DAY)VALUES('123','102','10-JAN-2016');
INSERT INTO RESERVE(SID,BID,DAY)VALUES('125','103','10-JAN-2016');
SELECT *FROM RESERVE;

SELECT SNAME FROM SAILOR JOIN RESERVE USING(SID) WHERE RESERVE.BID=103;
SELECT SAILOR.SNAME FROM RESERVE JOIN SAILOR ON RESERVE.SID=BOAT.BID WHERE BOAT.COLOR='RED' OR BOAT COLOR='GREEN';