CREATE TABLE BOAT(
BID INT NOT NULL,
BNAME VARCHAR(10) NOT NULL,
COLOR VARCHAR(10) NOT NULL,
PRIMARY KEY(BID)
);

CREATE TABLE SAILOR(
SID INT NOT NULL,
SNAME VARCHAR(10) NOT NULL,
RATING INT NOT NULL,
AGE INT NOT NULL,
PRIMARY KEY(SID)
);

CREATE TABLE RESERVE(
BID INT NOT NULL,
SID INT NOT NULL,
DAY DATE NOT NULL,
CONSTRAINT MAYA PRIMARY KEY
(
SID,
BID
),
FOREIGN KEY(SID) REFERENCES SAILOR(SID),
FOREIGN KEY(BID) REFERENCES BOAT(BID)
);

INSERT INTO BOAT(BID,BNAME,COLOR) VALUES(401,'ROFF','RED');
INSERT INTO BOAT(BID,BNAME,COLOR) VALUES(402,'BORAK','BLACK');
INSERT INTO BOAT(BID,BNAME,COLOR) VALUES(403,'EAGLE','BLUE');
INSERT INTO BOAT(BID,BNAME,COLOR) VALUES(404,'ROFF_ROFF','GREEN');

INSERT INTO SAILOR(SID,SNAME,RATING,AGE) VALUES(21,'MAYA',5.5,23);
INSERT INTO SAILOR(SID,SNAME,RATING,AGE) VALUES(22,'KAYA',4,26);
INSERT INTO SAILOR(SID,SNAME,RATING,AGE) VALUES(23,'CHAYA',3,26);
INSERT INTO SAILOR(SID,SNAME,RATING,AGE) VALUES(24,'RAYA',4.2,18);

INSERT INTO RESERVE(BID,SID,DAY) VALUES(401,22,'13-FEB-2016');
INSERT INTO RESERVE(BID,SID,DAY) VALUES(401,23,'13-FEB-2016');
INSERT INTO RESERVE(BID,SID,DAY) VALUES(403,24,'14-FEB-2016');
INSERT INTO RESERVE(BID,SID,DAY) VALUES(404,21,'16-FEB-2016');

SELECT SAILOR.SID,BOAT.BID,SNAME,BNAME,COLOR,DAY
FROM RESERVE
JOIN SAILOR ON RESERVE.SID = SAILOR.SID
JOIN BOAT ON RESERVE.BID =BOAT.BID WHERE BOAT.BID=103;

SELECT SAILOR.SID,BOAT.BID,SNAME,BNAME,COLOR,DAY
FROM RESERVE
JOIN SAILOR ON RESERVE.SID = SAILOR.SID
JOIN BOAT ON RESERVE.BID =BOAT.BID WHERE BOAT.COLOR='RED' OR BOAT.COLOR='GREEN';

Select SNAME,AGE 
from SAILOR 
where AGE = (select max(AGE) from SAILOR);

Select SNAME,AGE 
from SAILOR 
where AGE = (select MIN(AGE) from SAILOR);
